language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=NavKit.xcodeproj
  - SCHEME=NavKit
  - SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 7 Plus"
before_install:
    - gem install xcpretty -N
    - gem install slather --no-ri --no-rdoc
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty -c;
after_success:
    - slather
